### ISSUE TITLE
Cannot find module 'humanize-plus'

### ISSUE THREAD

**Issue by hurcy** [yona-projects/yona-export#3]
next 브랜치에서 npm install 후에 이런 에러가 발생합니다.

Error: Cannot find module 'humanize-plus'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/hcinyoung/data/dev/yona-export/app/header.js:2:1)
    at Module._compile (module.js:569:30)
    at loader (/home/hcinyoung/data/dev/yona-export/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/hcinyoung/data/dev/yona-export/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)

**Comment by doortts** [comment]
저 메시지가 install 할때 발생하나요? 아니면 실행할때 발생하나요?

**Comment by hurcy** [comment]
실행할 때 발생해요. npm install에서 저 모듈이 빠져있는것 같습니다.

**Comment by doortts** [comment]
@hurcy 
git pull 받으시고 npm install 을 다시 한 번 해주셔야 해요
https://github.com/yona-projects/yona-export/blob/master/package.json#L24 에 의존 package 로는 지정되어 있어요

**Comment by hurcy** [comment]
넵 감사합니다.
